import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.jsx
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Header with logo */}
        <header className="bg-white shadow p-4 flex items-center justify-between">
          <div className="text-xl font-bold text-black">
            <a href="/">MyLogo</a>  {/* You can replace with <Image> if using next/image */}
          </div>
        </header>

        {/* Main Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
