import Link from 'next/link';  
import { Geist, Geist_Mono } from "next/font/google";  
import "./globals.css"; 
import LogoutButton from "./components/LogoutButton"; 

const geistSans = Geist({  
  variable: "--font-geist-sans",  
  subsets: ["latin"],  
});  

const geistMono = Geist_Mono({  
  variable: "--font-geist-mono",  
  subsets: ["latin"],  
});  

export const metadata = {  
  title: "Create Next App",  
  description: "Generated by create next app",  
};  

export default function RootLayout({ children }) {  
  return (  
    <html lang="en">  
      <body>  
        <header className="bg-white shadow p-4 flex items-center justify-between">  
          <div className="text-xl font-bold text-black">  
            <Link href="/">  
             
            </Link>  
          </div>  
    
        </header>  

        <main>{children}</main>  
      </body>  
    </html>  
  );  
}  
